# Generated by Django 4.2.2 on 2023-07-01 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Landlord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Mr", "Mr"),
                            ("Ms", "Ms"),
                            ("Mrs", "Mrs"),
                            ("Miss", "Miss"),
                            ("Dr", "Dr"),
                        ],
                        max_length=4,
                    ),
                ),
                ("first_name", models.TextField()),
                ("middle_name", models.TextField(blank=True, null=True)),
                ("last_name", models.TextField()),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="someone@example.com",
                        max_length=254,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house_number", models.TextField()),
                ("street", models.TextField()),
                ("town", models.TextField()),
                ("postcode", models.TextField(max_length=8)),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Mr", "Mr"),
                            ("Ms", "Ms"),
                            ("Mrs", "Mrs"),
                            ("Miss", "Miss"),
                            ("Dr", "Dr"),
                        ],
                        max_length=4,
                    ),
                ),
                ("first_name", models.TextField()),
                ("middle_name", models.TextField(blank=True, null=True)),
                ("last_name", models.TextField()),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="someone@example.com",
                        max_length=254,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tenancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime(2023, 7, 1, 12, 18, 57, 960319)
                    ),
                ),
                ("end_date", models.DateField()),
                ("rent", models.FloatField()),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentals.landlord",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentals.property",
                    ),
                ),
                ("tenants", models.ManyToManyField(to="rentals.tenant")),
            ],
            options={
                "verbose_name_plural": "Tenancies",
                "ordering": ["start_date"],
            },
        ),
    ]
