# Generated by Django 4.2.2 on 2023-07-01 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landlord",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 1, 12, 21, 15, 804632)
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
