# Generated by Django 4.2.2 on 2023-07-01 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_alter_landlord_email_alter_tenancy_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Studio", "Studio"),
                    ("Flat", "Flat"),
                    ("Maisonette", "Maisonette"),
                    ("Terrace", "Terrace"),
                    ("End terrace", "End Of Terrace"),
                    ("Bungalow", "Bungalow"),
                    ("Cottage", "Cottage"),
                    ("Semi-detatched", "Semi Detatched"),
                    ("Detached", "Detatched"),
                    ("Mansion", "Mansion"),
                ],
                default="Semi-detached",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 1, 21, 1, 9, 859284)
            ),
        ),
    ]
