# Generated by Django 4.2.2 on 2023-07-02 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_property_property_type_alter_tenancy_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Studio", "Studio"),
                    ("Flat", "Flat"),
                    ("Maisonette", "Maisonette"),
                    ("Terrace", "Terrace"),
                    ("End terrace", "End Of Terrace"),
                    ("Bungalow", "Bungalow"),
                    ("Cottage", "Cottage"),
                    ("Semi-detached", "Semi Detached"),
                    ("Detached", "Detatched"),
                    ("Mansion", "Mansion"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 2, 20, 57, 32, 17192)
            ),
        ),
    ]
