# Generated by Django 4.2.2 on 2023-07-08 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_alter_tenancy_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["street"], "verbose_name_plural": "Properties"},
        ),
        migrations.AddField(
            model_name="property",
            name="landlord",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rentals.landlord",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Studio", "Studio"),
                    ("Flat", "Flat"),
                    ("Maisonette", "Maisonette"),
                    ("Terrace", "Terrace"),
                    ("End terrace", "End Of Terrace"),
                    ("Bungalow", "Bungalow"),
                    ("Cottage", "Cottage"),
                    ("Semi-detached", "Semi Detached"),
                    ("Detached", "Detatched"),
                    ("Mansion", "Mansion"),
                    ("Land", "Land"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rentals.landlord",
            ),
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 8, 17, 9, 57, 81311)
            ),
        ),
    ]
