# Generated by Django 4.2.2 on 2023-07-08 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0007_alter_property_options_property_landlord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rentals.landlord",
            ),
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 8, 18, 14, 56, 215175)
            ),
        ),
    ]
