# Generated by Django 4.2.2 on 2023-07-09 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0010_alter_landlord_options_alter_tenant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenancy",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 9, 21, 54, 54, 259477)
            ),
        ),
    ]
