# Generated by Django 4.2.2 on 2023-07-10 21:29

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0011_alter_tenancy_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contractor_type",
                    models.CharField(
                        choices=[("Person", "Person"), ("Company", "Company")],
                        max_length=10,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Plumbing", "Plumbing"),
                            ("Electrician", "Electrician"),
                            ("Locksmith", "Locksmith"),
                            ("Cleaning services", "Cleaner"),
                            ("Gardener", "Gardener"),
                            ("Builder", "Builder"),
                            ("General services", "General"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company_name",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("first_name", models.TextField(blank=True, max_length=50, null=True)),
                ("last_name", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("website", models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 10, 22, 29, 54, 591146)
            ),
        ),
    ]
